export const GET_MOVIES_DETAILS = 'GET_MOVIES_DETAILS';
export const GET_MOVIES_DETAILS_SUCCESS = 'GET_MOVIES_DETAILS_SUCCESS';
export const GET_MOVIES_DETAILS_FAILURE = 'GET_MOVIES_DETAILS_FAILURE';
