export const GET_MOVIE_BY_QUERY = 'GET_MOVIE_BY_QUERY';
export const GET_MOVIE_BY_QUERY_SUCCESS = 'GET_MOVIE_BY_QUERY_SUCCESS';
export const GET_MOVIE_BY_QUERY_FAILURE = 'GET_MOVIE_BY_QUERY_FAILURE';
